config/routes.rb
Rails.application.routes.draw do
  
  root to: "tops#index"
  resources :tops, only: [:index, :show]
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
      get 'thanks'
    end
  end
  resources :users, only: [:index, :show]
  resources :themes, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]


end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    if @like.save
      redirect_to "/posts/#{params[:post_id]}"
    end
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    if @like.destroy
      redirect_to "/posts/#{params[:post_id]}"
    end
  end


end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_likes_favorites.html.haml
.likes-favorites
  - if user_signed_in? && @post.created_at > Time.zone.today.beginning_of_day #今日の投稿があれば
    - if current_user.already_liked?(@post) #いいね!済なら 取消 表示
      %span.like-push.already-liked
        = link_to post_like_path(@post), method: :delete, class: "like-submit" do
          いいね取消
        = @likes_count
      - if current_user.already_favorited?(@post)
        %span.fav-push.already-faved
          = link_to post_favorite_path(@post), method: :delete, class: "like-submit" do
            お気に入り解除
          = @favorites_count
      - else
        %span.fav-push
          = link_to post_favorites_path(@post), method: :post, class: "like-submit" do
            お気に入り追加
          = @favorites_count
    - elsif current_user.id == @post.user.id #自分の投稿なら
      %span.like-push-time-over
        %span.like-submit
          いいね獲得数
        = @likes_count
      %span.like-push-time-over
        %span.fav-submit
          お気に入りされた数
        = @favorites_count
    - else #まだいいね!してなければ いいね! 表示
      %span.like-push
        = link_to post_likes_path(@post), method: :post, class: "like-submit" do
          いいね!
        = @likes_count
      - if current_user.already_favorited?(@post)
        %span.fav-push.already-faved
          = link_to post_favorite_path(@post), method: :delete, class: "like-submit" do
            お気に入り解除
          = @favorites_count
      - else
        %span.fav-push
          = link_to post_favorites_path(@post), method: :post, class: "like-submit" do
            お気に入り追加
          = @favorites_count

  - elsif user_signed_in? && @post.created_at < Time.zone.today.beginning_of_day #昨日以前
    %span.like-push-time-over
      %span.like-submit
        いいね集計済
      = @likes_count
    - if current_user.already_favorited?(@post)
      %span.fav-push.already-faved
        = link_to post_favorite_path(@post), method: :delete, class: "like-submit" do
          お気に入り解除
        = @favorites_count
    - elsif current_user.id == @post.user.id #自分の投稿なら
      %span.like-push-time-over
        %span.fav-submit
          お気に入りされた数
        = @favorites_count
    - else
      %span.fav-push
        = link_to post_favorites_path(@post), method: :post, class: "like-submit" do
          お気に入り追加
        = @favorites_count

  - else #未ログイン → サインイン画面へ進む
    %span.like-push
      = link_to new_user_registration_path, class: "like-submit" do
        いいね!
      = @likes_count
    %span.fav-push
      = link_to new_user_registration_path, class: "like-submit" do
        お気に入り追加
      = @favorites_count