config/routes.rb
Rails.application.routes.draw do
  
  root to: "tops#index"
  resources :tops, only: [:index, :show]
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks',
  }
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
      get 'thanks'
    end
  end
  resources :users, only: [:index, :show]
  resources :themes, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
 class Post < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :favorites, dependent: :destroy
  has_many :fav_posts, through: :favorites, source: :user
  has_many :post_themes, dependent: :destroy
  has_many :themes, through: :post_themes

  validates :title, :image, presence: true

  mount_uploader :image, ImageUploader


  def self.search(search)
    return Post.all unless search
    Post.where('title collate utf8_unicode_ci LIKE(?)', "%#{search}%")
  end

  def self.best_post_for_all
    Post.find(Like.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
  end

  def self.create_today_ranks
    Post.find(Like.group(:post_id).order('count(post_id) desc').where(created_at: Time.zone.today.beginning_of_day..Time.zone.today.end_of_day).limit(3).pluck(:post_id))
  end

  def self.todays_post
    Post.find(Like.group(:post_id).order('count(post_id) desc').where(created_at: Time.zone.yesterday.beginning_of_day..Time.zone.yesterday.end_of_day).pluck(:post_id))
  end


end

app/models/post_theme.rb
class PostTheme < ApplicationRecord
  belongs_to :post
  belongs_to :theme
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user

  belongs_to :user, optional: true
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :post_themes
  has_many :posts, through: :post_themes
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :sns_credentials
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :favorites, dependent: :destroy
  has_many :fav_posts, through: :favorites, source: :post
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  validates :nickname, presence: true

  mount_uploader :avator, ImageUploader

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  def already_favorited?(post)
    self.favorites.exists?(post_id: post.id)
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    if @like.save
      redirect_to "/posts/#{params[:post_id]}"
    end
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    if @like.destroy
      redirect_to "/posts/#{params[:post_id]}"
    end
  end


end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  
  def index
  end

  def show
    @theme = Theme.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html+mobile.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title OneDPC
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css", rel: "stylesheet"}
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js", type: "text/javascript"}



  %body


    %header.mobile-header
      .mobile-header__logo
        = link_to posts_path, class: "mobile-header__logo--toppage-link" do
          ONE DPC
      %button.btn_menu{ type: "button" }
        %span.btn_text 
          %i.fa.fa-bars
      %nav.mobile-header__slide-menu
        %ul
          - unless user_signed_in?
            %li.mobile-header__slide-menu__list= link_to "新規登録", new_user_registration_path, class: "side-menu-list"
            %li.mobile-header__slide-menu__list= link_to "サインイン", new_user_session_path, class: "side-menu-list"
            %li.mobile-header__slide-menu__list= link_to "ONE DPCとは", "/tops/show", class: "side-menu-list"
          - else
            %li.mobile-header__slide-menu__list= link_to "マイページ", "/users/#{current_user.id}", class: "side-menu-list"
            %li.mobile-header__slide-menu__list= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "side-menu-list"
            %li.mobile-header__slide-menu__list= link_to "投稿する", "/posts/new", class: "side-menu-list"
            %li.mobile-header__slide-menu__list= link_to "テーマ一覧", "/themes", class: "side-menu-list"
            %li.mobile-header__slide-menu__list= link_to "ユーザー一覧", "/users", class: "side-menu-list"
            %li.mobile-header__slide-menu__list= link_to "ONE DPCとは", "/tops/show", class: "side-menu-list"

      - if user_signed_in?
        .user-name-on-header
          %span #{current_user.nickname}
          %br
          %span{style:"font-size:12px; color:gray;"} ログイン中
    - if user_signed_in?
      %ul.short-cut
        %li.short-cut__list
          = link_to search_posts_path, class: "short-cut__list__link" do
            %i.fa.fa-search 検索
        %li.short-cut__list
          = link_to new_post_path, class: "short-cut__list__link" do
            %i.fa.fa-camera
            投稿
        %li.short-cut__list
          = link_to user_path(current_user.id), class: "short-cut__list__link" do
            %i.fa.fa-user マイページ
    - else
      %ul.short-cut
        %li.short-cut__list
          = link_to search_posts_path, class: "short-cut__list__link" do
            %i.fa.fa-search 検索
        %li.short-cut__list
          = link_to "/tops/show", class: "short-cut__list__link" do
            %i.fa.fa-book
            ONE DPCとは
        %li.short-cut__list
          = link_to new_user_registration_path, class: "short-cut__list__link" do
            %i.fa.fa-user 新規登録

    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title ONEDPC
    = include_gon
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css", rel: "stylesheet"}
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js", type: "text/javascript"}


  %body


    %header.header
      .header__box
        = link_to "ONE DPC", "/posts", class: "onedpc-logo"
        - if user_signed_in?
          %ul.menu
            %li.menu__single.single1
              .pulldown 
                = current_user.nickname
              %ul.menu__second-level
                %li= link_to "マイページ", user_path(current_user.id), class: "pulldown-list"
                %li= link_to "アカウント編集", edit_user_registration_path, class: "pulldown-list"
                %li= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "pulldown-list"
            %li.menu__single.single2
              .pulldown 
                投稿関連
              %ul.menu__second-level
                %li= link_to "投稿する", new_post_path, class: "pulldown-list"
                %li= link_to "テーマ一覧", themes_path, class: "pulldown-list"
                %li= link_to "ユーザー一覧", users_path, class: "pulldown-list"
            %li.menu__single.single2
              .pulldown 
                アプリ説明
              %ul.menu__second-level
                %li= link_to "ONE DPCとは", "/tops/show", class: "pulldown-list"
        - else
          %ul.menu
            %li.menu__single.single2
              .pulldown 
                ユーザーメニュー
              %ul.menu__second-level
                %li= link_to "新規登録", new_user_registration_path, class: "pulldown-list"
                %li= link_to "サインイン", new_user_session_path, class: "pulldown-list"
            %li.menu__single.single2
              .pulldown 
                アプリ説明
              %ul.menu__second-level
                %li= link_to "ONE DPCとは", "/tops/show", class: "pulldown-list"


    = yield

app/views/layouts/tops.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title title -- OneDPC
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shared/_footer.html.haml
%footer.footer
  .footer__contents
    .footer__contents__developer-msg
      %h3.footer__contents__developer-msg--heading ONE DPC (One Day Photo Contest) アプリ概要
      %p.footer__contents__developer-msg--contest-description
        カメラ初心者、アマチュア写真愛好家向けのフォトコンテストアプリ。
        %br
        ONE DPCとは one Day, one Photo, one Contest の略であり、一日限定フォトコンテストの意味。
        %br
        %br
        ルールは以下の通り。
        %br
        ①ユーザーがその日のテーマに合わせて写真を投稿。
        %br
        ②投稿へのいいねの数がその日一番多い画像がコンテストの優勝作品となり、翌日の「今日の一枚」として表示される。
        %br
      %ul.footer__contents__developer-msg--links
        %li
          公開中
          = link_to "開発者のポートフォリオサイト", "https://zen-stonebraker-c82f4a.netlify.com/"
        %button.inquiry-form-btn
          お問い合わせフォーム
    .inquiry-form-wrapper
      %form{action: "https://api.staticforms.xyz/submit", method: :post, class: "inquiry-form", id: "inquiry-form"}
        %h4.inquiry-form__title お名前
        %input{name: "name", placeholder: "", type: "text", class: "inquiry-form__input", required: true}
        %h4.inquiry-form__title メールアドレス
        %input{name: "email", placeholder: "", type: "text", class: "inquiry-form__input", required: true}
        %h4.inquiry-form__title メッセージ
        %textarea{name: "message", placeholder: "", class: "inquiry-form__input", required: true}
        %input{name: "honeypot", style: "display:none", type: "text", class: "inquiry-form__input"}
        %input{name: "accessKey", type: "hidden", value: "a11fa1c6-a381-4734-9057-443a8d60c397", class: "inquiry-form__input"}
        %input{name: "subject", type: "hidden", value: "Contact us from - example.com", class: "inquiry-form__input"}
        %input{name: "replyTo", type: "hidden", value: "@", class: "inquiry-form__input"}
        %input{name: "redirectTo", type: "hidden", value: "http://3.115.17.18:4000/posts/thanks", class: "inquiry-form__input"}
        %input{type: "submit", value: "送信", class: "inquiry-form__submit"}

app/views/shared/_header_bottom.html.haml
.main-top__box
  %p.main-top__box--todays-theme#mobile-todays-theme
    %span{style: "font-weight:bold;"}
      本日のテーマ：
      = link_to theme_path(@today_theme.id), class: "theme-link" do
        %span.theme-tag.tag1
          = @today_theme.name  
  = form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |f|
    = f.text_field :keyword, placeholder: "投稿を検索する", type: 'text', required: true, class: "search-input"
    %span<>
    = button_tag type: :submit,class:"search-btn" do
      %i.fa.fa-search
  %span.limit
    ※投稿および投票締め切り本日24時
    %br
    %span#view_clock
      :javascript
        timerID = setInterval('clock()',500); //0.5秒毎にclock()を実行

        function clock() {
          document.getElementById("view_clock").innerHTML = getNow();
        }

        function getNow() {
          var now = new Date();
          var year = now.getFullYear();
          var mon = now.getMonth()+1;
          var day = now.getDate();
          var you = now.getDay();
          var hour = now.getHours();
          var min = now.getMinutes();
          var sec = now.getSeconds();

          var youbi = new Array("日","月","火","水","木","金","土");

          var s = year + "年" + mon + "月" + day + "日("+ youbi[you] +")" + hour + "時" + min + "分" + sec + "秒"; 
          return s;
        }

app/views/shared/_new_post.html.haml
- if signed_in?
  - if current_user.posts.where("created_at > ?", Time.zone.today.beginning_of_day).present?
    = link_to new_post_path, class: "new-post-icon re-post" do
      %span.new-post-icon_text
        やり直す
      %span.new-post-icon__camera-icon
        %i.fa.fa-camera
  - else
    = link_to new_post_path, class: "new-post-icon" do
      %span.new-post-icon_text
        投稿する
      %span.new-post-icon__camera-icon
        %i.fa.fa-camera
- else
  = link_to new_user_session_path, class: "new-post-icon non-user" do
    %span.new-post-icon_text
      新規登録

app/views/shared/_page_back.html.haml
.page-back-or-page-index
  = link_to "< ひとつ前のページ", :back
  ーー
  = link_to "投稿一覧へ戻る >", "/posts", class:"back-to-toppage"

app/views/simple_calendar/_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    %span.calendar-title
      = t('date.month_names')[start_date.month]
      = start_date.year
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          - if day.wday == 0
            %th= t('date.abbr_day_names')[day.wday]
          - elsif day.wday == 6
            %th= t('date.abbr_day_names')[day.wday]
          - else
            %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        = content_tag :tr, class: calendar.tr_classes_for(week) do
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block)
                - capture_haml(day, sorted_events.fetch(day, []), &block)
              - else
                - block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_month_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    %span.calendar-title
      = t('date.month_names')[start_date.month]
      = start_date.year
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          - if day.wday == 0
            %th.youbi-name.sun= t('date.abbr_day_names')[day.wday]
          - elsif day.wday == 6
            %th.youbi-name.sat= t('date.abbr_day_names')[day.wday]
          - else
            %th.youbi-name>
            ,&gt;#{t('date.abbr_day_names')[day.wday]}
  %tbody
    - date_range.each_slice(7) do |week|
      %tr{:style => "font-weight:bold;"}
        - week.each do |day|
          = content_tag :td, class: calendar.td_classes_for(day) do
            - if defined?(Haml)  respond_to?(:block_is_haml?)  block_is_haml?(block)
              - capture_haml(day, sorted_events.fetch(day, []), block)
            - else
              - block.call day, sorted_events.fetch(day, [])

app/views/simple_calendar/_week_calendar.html.haml
.simple-calendar
  .calendar-heading
    = link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view
    - if calendar.number_of_weeks == 1
      %span.calendar-title
        Week 
        = calendar.week_number
    - else
      %span.calendar-title
        Week 
        = calendar.week_number - calendar.end_week
    = link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view
  %table.table.table-striped
    %thead
      %tr
        - date_range.slice(0, 7).each do |day|
          %th= t('date.abbr_day_names')[day.wday]
    %tbody
      - date_range.each_slice(7) do |week|
        %tr
          - week.each do |day|
            = content_tag :td, class: calendar.td_classes_for(day) do
              - if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block)
                - capture_haml(day, sorted_events.fetch(day, []), &block)
              - else
                - block.call day, sorted_events.fetch(day, [])